<?php
// includes/db.php
// Set default timezone to Indian Standard Time (IST)
date_default_timezone_set('Asia/Kolkata');

// Credentials loaded from:
//   - includes/secrets.php (generated by GitHub Actions on live server)
//   - includes/env.php (local dev, gitignored)
// Both files use define() which is InfinityFree compatible.

// Load secrets from CI/CD pipeline (live server)
if (file_exists(__DIR__ . '/secrets.php')) {
    require_once __DIR__ . '/secrets.php';
}

// Load local dev overrides (only used when secrets.php doesn't exist)
if (file_exists(__DIR__ . '/env.php')) {
    require_once __DIR__ . '/env.php';
}

// Fallback defaults (safe for local XAMPP)
if (!defined('DB_HOST'))          define('DB_HOST',          'localhost');
if (!defined('DB_NAME'))          define('DB_NAME',          'money_management');
if (!defined('DB_USER'))          define('DB_USER',          'root');
if (!defined('DB_PASS'))          define('DB_PASS',          '');
if (!defined('SESSION_LIFETIME')) define('SESSION_LIFETIME', 900);
if (!defined('BASE_URL'))         define('BASE_URL',         '/PROJECT M/');

error_reporting(0);
ini_set('display_errors', 0);

try {
    $pdo = new PDO(
        "mysql:host=" . DB_HOST . ";dbname=" . DB_NAME . ";charset=utf8mb4",
        DB_USER,
        DB_PASS,
        [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false
        ]
    );
    // Sync MySQL session timezone with Indian Standard Time (+05:30)
    $pdo->exec("SET time_zone = '+05:30'");
} catch (PDOException $e) {
    http_response_code(500);
    echo json_encode(['status' => 'error', 'message' => 'Database connection failed.']);
    exit;
}
