<?php
// includes/db.php
// Set default timezone to Indian Standard Time (IST)
date_default_timezone_set('Asia/Kolkata');

// Credentials loaded from:
//   - includes/secrets.php (generated by GitHub Actions on live server)
//   - includes/env.php (local dev, gitignored)
// Both files use define() which is InfinityFree compatible.

// Load secrets from CI/CD pipeline (live server)
if (file_exists(__DIR__ . '/secrets.php')) {
    require_once __DIR__ . '/secrets.php';
}

// Load local dev overrides (only used when secrets.php doesn't exist)
if (file_exists(__DIR__ . '/env.php')) {
    require_once __DIR__ . '/env.php';
}

// Ensure all required database constants are defined
$required_constants = ['DB_HOST', 'DB_NAME', 'DB_USER', 'DB_PASS'];
$missing = [];
foreach ($required_constants as $constant) {
    if (!defined($constant)) {
        $missing[] = $constant;
    }
}

if (!empty($missing)) {
    http_response_code(500);
    echo json_encode([
        'status' => 'error',
        'message' => 'System configuration error: Missing definitions for ' . implode(', ', $missing)
    ]);
    exit;
}

// Fallback session and base URL defaults if not specified in secrets or env
if (!defined('SESSION_LIFETIME')) define('SESSION_LIFETIME', 900);
if (!defined('BASE_URL'))         define('BASE_URL',         '/');

error_reporting(0);
ini_set('display_errors', 0);

try {
    $pdo = new PDO(
        "mysql:host=" . DB_HOST . ";dbname=" . DB_NAME . ";charset=utf8mb4",
        DB_USER,
        DB_PASS,
        [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES => false
        ]
    );
    // Sync MySQL session timezone with Indian Standard Time (+05:30)
    $pdo->exec("SET time_zone = '+05:30'");
} catch (PDOException $e) {
    http_response_code(500);
    if (strpos($_SERVER['HTTP_ACCEPT'] ?? '', 'application/json') !== false
     || strpos($_SERVER['CONTENT_TYPE'] ?? '', 'application/json') !== false) {
        echo json_encode(['status' => 'error', 'message' => 'Database connection failed.']);
    } else {
        $base_path = defined('BASE_URL') ? BASE_URL : '/';
        header('Location: ' . $base_path . 'error.php?code=db');
    }
    exit;
}
